version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - './certbot/www:/var/www/certbot/:ro'
    depends_on:
      - certbot
    networks:
      - dev

  certbot:
    image: certbot/certbot
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot --email godnestywork@gmail.com --agree-tos --no-eff-email --force-renewal -d valdemir.ru -d www.valdemir.ru -d valdemir.online -d www.valdemir.online; sleep 12h & wait $${!}; done;'"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev